name: SSPanel_Auto_Checkin

on:
    push:
        branches:
            - master
    schedule:
        - cron: 20 18 * * *
    watch:
        types: 
            - started

env:
    TZ: Asia/Shanghai
    DOMAIN: ${{secrets.DOMAIN}}
    USERNAME: ${{secrets.USERNAME}}
    PASSWD: ${{secrets.PASSWD}}
    PUSH_KEY: ${{secrets.PUSH_KEY}}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            
            - name: Install depends
              run: |
                sudo apt-get update
                sudo apt-get -y install curl jq

            - name: Request API
              run: |
                bash ssp-autocheckin.sh
